namespace Heloc.Models.InputCopyBookModels.HelocBillingModels
{
    public class MasterFileDataPart1Model
    {

        public string B650_Rcd_Id { get; set; }
        public string B650_Inst { get; set; }
        public string B650_Acct_No { get; set; }
        public string B650_Seq_No { get; set; }
        public string B650_Ml_Cr_Ins_Pymt_Packeddata { get; set; }
        public string B650_Ml_Prin_Bal_Packeddata { get; set; }
        public string B650_Ml_Esc_Bal_Packeddata { get; set; }
        public string B650_Ml_Ln_Type_Packeddata { get; set; }
        public string B650_Ml_Sub_Type_Packeddata { get; set; }
        public string B650_Ml_P_I_Pymt_Packeddata { get; set; }
        public string B650_Ml_Esc_Pymt_Packeddata { get; set; }
        public string B650_Ml_Inv_Own_Cd_Packeddata { get; set; }
        public string B650_Ml_Inv_All { get; set; }
        public string B650_Ml_Inv_Code_Packeddata { get; set; }
        public string B650_Inv_Name { get; set; }
        public string B650_Ml_Inv_Block_Packeddata { get; set; }
        public string B650_Ml_Inv_Pc_Owned_Packeddata { get; set; }
        public string B650_Ml_Inv_Rate_Packeddata { get; set; }
        public string B650_Ml_Inv_Sv_Code_Packeddata { get; set; }
        public string B650_Ml_Inv_Sv_Fee_Packeddata { get; set; }
        public string B650_Ml_Inv_Acnt { get; set; }
        public string B650_Ml_Inv_Fill { get; set; }
        public string B650_Ml_Lip_La_Date { get; set; }
        public string B650_Ml_Esc_Var_Packeddata { get; set; }
        public string B650_Ml_Prop_Cd_Packeddata { get; set; }
        public string B650_Ml_Int_Pd_Ytd_Packeddata { get; set; }
        public string B650_Ml_Pur_Code_Packeddata { get; set; }
        public string B650_Ml_Unap_Fund_Cd { get; set; }
        public string B650_Ml_State_Packeddata { get; set; }
        public string B650_Ml_Due_Date { get; set; }
        public string B650_Ml_Pymts_Due_Amt_Packeddata { get; set; }
        public string B650_Ml_Pymts_Due_Ctr_Packeddata { get; set; }
        public string B650_Ml_Late_Chg_Amt_Packeddata { get; set; }
        public string B650_Ml_Late_Chg_Due_Packeddata { get; set; }
        public string B650_Prepaid_Flag { get; set; }
        public string B650_Ml_Esc_Int_Ytd_Packeddata { get; set; }
        public string B650_Ml_Run_Date { get; set; }
        public string B650_Primary_Name { get; set; }
        public string B650_Secondary_Name { get; set; }
        public string B650_Mail_Adrs_1 { get; set; }
        public string B650_Mail_Adrs_2 { get; set; }
        public string B650_Mail_City { get; set; }
        //public string Filler { get; set; }
        public string B650_Mail_State { get; set; }
        public string B650_Mail_Zip { get; set; }
        public string B650_Appl_Adrs_1 { get; set; }
        public string B650_Appl_Adrs_2 { get; set; }
        public string B650_Appl_City { get; set; }
        public string B650_Appl_State { get; set; }
        public string B650_Appl_Zip { get; set; }
        public string B650_Bill_Pmt_Dte { get; set; }
        public string B650_Bill_Pmt_Amt_Packeddata { get; set; }
        public string B650_Ml_Branch_Packeddata { get; set; }
        public string B650_Bill_Total_Due_Packeddata { get; set; }
        public string B650_Bill_Lc_Packeddata { get; set; }
        public string B650_Ml_Pymt_Cyc_Packeddata { get; set; }
        public string B650_Ml_W_Flag_Packeddata { get; set; }
        public string B650_Ml_Dist_Mail_Cd { get; set; }
        public string B650_Ml_Last_Actvty_Dt_Packeddata { get; set; }
        public string B650_Ml_Apr_Rate_Packeddata { get; set; }
        public string B650_Ml_Neg_Amort_Taken_Packeddata { get; set; }
        public string B650_Ml_Grace_Days_Packeddata { get; set; }
        public string B650_Ml_Taxpd_Ytd_Packeddata { get; set; }
        public string B650_Ml_Pd_To_Date { get; set; }
        public string B650_Tape_Cur_Due_Date { get; set; }
        public string B650_Ml_Prn_Var_Packeddata { get; set; }
        public string B650_Tape_Uncol_Int { get; set; }
        public string B650_Tape_Note_Rate_Packeddata { get; set; }
        public string B650_Tape_Neg_Am_Ass_Ytd_Packeddata { get; set; }
        public string B650_Tape_Neg_Am_Paid_Ytd_Packeddata { get; set; }
        public string B650_Tape_Rate_Ov_Packeddata { get; set; }
        public string B650_Tape_Org_Rate_Ov_Packeddata { get; set; }
        public string B650_Tape_Bill_Number_Packeddata { get; set; }
        public string B650_Ml_Bank_Trans_Packeddata { get; set; }
        public string B650_Ml_Withhold_Ytd_Packeddata { get; set; }
        public string B650_Ml_Neg_Amort_Flag_Packeddata { get; set; }
        public string B650_Tape_Int_Due_Packeddata { get; set; }
        public string B650_Ml_Sec_Mort_Cd_Packeddata { get; set; }
        public string B650_Ml_2Nd_Acct_No_Packeddata { get; set; }
        public string B650_Ml_2Nd_Bill_Amt_Packeddata { get; set; }
        public string B650_Ml_Fees_Packeddata { get; set; }
        public string B650_Tape_Past_Payments { get; set; }
        public string B650_Tape_Past_Date { get; set; }
        public string B650_Tape_Reg_Amt_Packeddata { get; set; }
        public string B650_Tape_Late_Amt_Packeddata { get; set; }
        public string B650_Ml_Billing_Opt { get; set; }
        public string B650_Tape_Alt_Ov_Un_Packeddata { get; set; }
        public string B650_Tape_Indx_Dt_Packeddata { get; set; }
        public string B650_Tape_Curr_Indx_Packeddata { get; set; }
        public string B650_Tape_Mkt_Ov_Un_Packeddata { get; set; }
        public string B650_Tape_Int_Pmt { get; set; }
        public string B650_Tape_Amort_Pmt_Packeddata { get; set; }
        public string B650_Ml_Bill_Method_Packeddata { get; set; }
        public string B650_T9_Ach_Acct_No { get; set; }
        public string B650_Tape_Anl_Indx_Rte_Packeddata { get; set; }
        public string B650_Ml_Tape_Int_Meth_Packeddata { get; set; }
        public string B650_T9_Cross_Sell_Flag { get; set; }
        public string B650_Ml_Mult_Loan_Flag { get; set; }
        public string B650_Prim_Social_Fill { get; set; }
        public string B650_Primary_Social_Sec { get; set; }
        public string B650_Tape_Repay_Amt_Due_Packeddata { get; set; }
        public string B650_Tape_Amort_Fee_Pymt_Packeddata { get; set; }
        public string B650_Repy_Plan_Due_Date_Packeddata { get; set; }
        public string B650_Repy_Remain_Bal { get; set; }
        public string B650_Ml_Email_Bill_Ind { get; set; }
        public string B650_Borrower_Email_Adr { get; set; }
        public string B650_Info_Prim_Fax_Phone_Packeddata { get; set; }
        public string B650_Info_Prim_Cell_Ph_Packeddata { get; set; }
        public string B650_T9_Direct_Mail { get; set; }
        public string B650_T9_Telemarket { get; set; }
        public string B650_Ml_Fees_New_Packeddata { get; set; }
        public string B650_Serv_Date { get; set; }
        public string B650_First_Stmt_Ind { get; set; }
        public string B650_Mail_Cd { get; set; }
        public string B650_Spec_Stmt_Req { get; set; }
        public string B650_Stop_1 { get; set; }
        public string B650_Opt_In_Flag { get; set; }
        public string B650_Opt_Out_Flag { get; set; }
        public string B650_Ml_Scnd_Email_Bill_Ind { get; set; }
        public string B650_First_Due_Dt { get; set; }
        public string B650_Mort_Ln_Flg { get; set; }
        public string B650_Purch_From_Name { get; set; }
        public string B650_Uncoll_Nsf_Fees { get; set; }
        public string B650_Uncoll_Ext_Fees { get; set; }
        public string B650_Prim_Home_Ph { get; set; }
        public string B650_V_Tax_Id { get; set; }
        public string B650_F_O_Flag_1 { get; set; }
        public string B650_F_O_Flag_2 { get; set; }
        public string B650_F_O_Flag_3 { get; set; }
        public string B650_F_O_Flag_4 { get; set; }
        public string B650_F_O_Flag_5 { get; set; }
        public string B650_Secondary_Social_Fill { get; set; }
        public string B650_Secondary_Social_Sec { get; set; }
        public string B650_Origin_Date { get; set; }
        public string B650_Int_Start_Dt { get; set; }
        public string B650_Term_Clos { get; set; }
        public string B650_Couns_Cd { get; set; }
        public string B650_Updated_Term { get; set; }
        public string B650_Modify_Date { get; set; }
        public string B650_Var_Rate { get; set; }
        public string B650_Name_Chg_Ind { get; set; }
        public string B650_Addr_Chg_Ind { get; set; }
        public string B650_Balloon_Date { get; set; }
        public string B650_Times_Delq_30 { get; set; }
        public string B650_Times_Delq_60 { get; set; }
        public string B650_Times_Delq_90 { get; set; }
        public string B650_Nsf_Tl_Ctr { get; set; }
        public string B650_Dem1_Prim_Birthdt { get; set; }
        public string B650_Dem1_Cb_Score_1 { get; set; }
        public string B650_Dem1_Cb_Score_2 { get; set; }
        public string B650_Dem1_Cb_Score_3 { get; set; }
        public string B650_Ext_Latest_Post_Dt { get; set; }
        public string B650_Ext_Tot_Act_Ext { get; set; }
        public string B650_Pre_Note { get; set; }
        public string B650_Prim_Work_Ph { get; set; }
        public string B650_Eoyh_Int_Gross { get; set; }
        public string B650_Foreclosure_Adv { get; set; }
        public string B650_Net_Investment { get; set; }
        public string B650_Orig_Dcnt_Amount { get; set; }
        public string B650_Tot_Pymts_Lol { get; set; }
        public string B650_Monthly_Int_Rate { get; set; }
        public string B650_Num_Days_Delq { get; set; }
        public string B650_Optn_Maint_Dt { get; set; }
        public string B650_Prior_Acnt_Nbr { get; set; }
        public string B650_Last_Pymt_Dt { get; set; }
        public string B650_Prim_Marital_Stat { get; set; }
        public string B650_Cls_Cd { get; set; }
        public string B650_Reo_Ind { get; set; }
        public string B650_Mat_Date { get; set; }
        public string B650_Pco_Taken { get; set; }
        public string B650_L_Flag { get; set; }
        public string B650_Stop_Code_2 { get; set; }
        public string B650_Stop_Code_3 { get; set; }
        public string B650_Fico_Score { get; set; }
        public string B650_Nsf_Indicator { get; set; }
        public string B650_Empl_Code { get; set; }
        public string B650_Audit_Date { get; set; }
        public string B650_Prim_Age { get; set; }
        public string B650_Scnd_Age { get; set; }
        public string B650_Realtr_Bldr { get; set; }
        public string B650_Usr_01_Packeddata { get; set; }
        public string B650_Tot_Fees_Due_Packeddata { get; set; }
        public string B650_Rd_Status { get; set; }
        public string B650_Int_Refi_Code { get; set; }
        public string B650_Usr_07 { get; set; }
        public string B650_Usr_36 { get; set; }
        public string B650_Ln_Ext_Extend_Int_Packeddata { get; set; }
        public string B650_Stmt_Flag { get; set; }
        public string B650_Stmt_Chg_Date { get; set; }
        public string B650_Accel_Apds_Part { get; set; }
        public string B650_Accel_Prog_Ind { get; set; }
        public string B650_Org_Code { get; set; }
        public string B650_Nimx_Plss_Entity { get; set; }
        public string B650_Mail_Country { get; set; }
        public string B650_Appl_Country { get; set; }
        public string B650_Lc_Assessed_Curr_Year_Packeddata { get; set; }
        public string B650_Lc_Paid_Curr_Year_Packeddata { get; set; }
        public string B650_Lc_Assessed_Prior_Year_Packeddata { get; set; }
        public string B650_Lc_Paid_ { get; set; }
        public string Prior_Year_Packeddata { get; set; }
        public string B650_Fees_Assessed_Curr_Year_Packeddata { get; set; }
        public string B650_Fees_Paid_Curr_Year_Packeddata { get; set; }
        public string B650_Fees_Assessed_Prior_Year_Packeddata { get; set; }
        public string B650_Fees_Paid_Prior_Year_Packeddata { get; set; }
        public string B650_Int_Charged_Ytd_Packeddata { get; set; }
        public string B650_Closing_Int_Ytd_Packeddata { get; set; }



        public string B650_Rec1_Prior_Bill_Dt_Packeddata { get; set; }
        public string B650_Rec1_Unpaid_Int_Packeddata { get; set; }
        public string B650_Rec1_Unpaid_Prin_Packeddata { get; set; }
        public string B650_Rec1_Unpaid_Esc_Packeddata { get; set; }
        public string B650_Rec1_Unpaid_Fees_Packeddata { get; set; }
        public string B650_Rec1_Unpaid_Ins_Packeddata { get; set; }
        public string B650_Rec1_Unpaid_Lc_Packeddata { get; set; }
        public string B650_Rec1_Unpaid_Adj_Int_Packeddata { get; set; }
        public string B650_Rec1_Unpaid_Adj_Ins_Packeddata { get; set; }

        public string B650_Rec1_Curr_Bill_Dt_Packeddata { get; set; }
        public string B650_Rec1_Curr_Due_Dt_Packeddata { get; set; }
        public string B650_Rec1_Curr_Int_Packeddata { get; set; }
        public string B650_Rec1_Curr_Prin_Packeddata { get; set; }

        public string B650_Rec1_Curr_Esc_Packeddata { get; set; }
        public string B650_Rec1_Curr_Fees_Packeddata { get; set; }

        public string B650_Rec1_Curr_Ins_Packeddata { get; set; }
        public string B650_Rec1_Curr_Lc_Packeddata { get; set; }
        public string B650_Rec1_Curr_Adj_Int_Packeddata { get; set; }
        public string B650_Int_Calc_Bal { get; set; }
        public string B650_Int_Calc_Meth { get; set; }
        public string B650_Pymt_Calc_Meth { get; set; }
        public string B650_Vend_Bill_Cd { get; set; }
        public string B650_Rec1_Int_Recd_Nobill { get; set; }
        public string B650_Rec1_Bill_Not_Pd_Lc { get; set; }
        public string B650_Pymt_Calc_Bal { get; set; }
        public string B650_Rec1_Curr_Adj_Ins_Packeddata { get; set; }

        public string B650_Rec1_Prior_Bill_Packeddata { get; set; }
        public string B650_Rec1_Prior_Due_Dt_Packeddata { get; set; }
        public string B650_Rec1_Prior_Int_Packeddata { get; set; }
        public string B650_Rec1_Prior_Prin_Packeddata { get; set; }
        public string B650_Rec1_Prior_Esc_Packeddata { get; set; }
        public string B650_Rec1_Prior_Fees_Packeddata { get; set; }
        public string B650_Rec1_Prior_Ins_Packeddata { get; set; }
        public string B650_Rec1_Prior_Lc_Packeddata { get; set; }
        public string B650_Rec1_Prior_Adj_Int_Packeddata { get; set; }
        public string B650_Rec1_Prior_Adj_Ins_Packeddata { get; set; }

        public string B650_Rec1_Prior_Ins_Pd_No_Bill_Packeddata { get; set; }
        public string B650_Rec1_Prior_Paid_Nobill_Lc_Packeddata { get; set; }
        public string B650_Rec1_Prior_Int_Pd_No_Bill_Packeddata { get; set; }
        public string B650_Rec1_Extra_Lc_Packeddata { get; set; }

        public string B650_Ib_Fr_Date_Packeddata { get; set; }
        public string B650_Ib_To_Date_Packeddata { get; set; }
        public string B650_Ib_Tbl_Rate_Packeddata { get; set; }
        public string B650_Ib_Int_Amt_Packeddata { get; set; }
        public string B650_Ib_Days_Packeddata { get; set; }
        public string B650_Ib_Pbal_Packeddata { get; set; }
        public string B650_Ib_Dper_Rate_Packeddata { get; set; }

        public string B650_Rec1_Average_Pbal_Packeddata { get; set; }
        public string B650_Bal_Subj_Packeddata { get; set; }
        public string B650_Original_Bal_Packeddata { get; set; }
        public string B650_Heloc_Tl_Finance_Chg_Packeddata { get; set; }
        public string B650_Min_Pymt_Packeddata { get; set; }
        public string B650_Nbr_Days_Packeddata { get; set; }
        public string B650_Base_Days_Packeddata { get; set; }
        public string B650_Tot_Adv_Packeddata { get; set; }
        public string B650_Dr_Per_End_Dt_Packeddata { get; set; }
        public string B650_Mper_Rt_Packeddata { get; set; }
        public string B650_Avail_Balance_Packeddata { get; set; }
        public string B650_Prev_Stmt_Bal_Packeddata { get; set; }
        public string B650_Pymt_Allocation { get; set; }
        public string B650_Ann_Perc_Rate_Packeddata { get; set; }
        public string B650_End_Date_Packeddata { get; set; }
        public string B650_Heloc_Amort_Pmt_Packeddata { get; set; }
        public string B650_Heloc_Tl_Fin_Chg { get; set; }
        public string B650_Cltl_Cd { get; set; }
        public string B650_Heloc_End_Stmt_Bal_Packeddata { get; set; }
        public string B650_Skip_Int_Def_Ltd_Packeddata { get; set; }

        public string B650_Sac_Camp_Id { get; set; }
        public string B650_Sac_Bal_Packeddata { get; set; }
        public string B650_Sac_Rate_Packeddata { get; set; }
        public string B650_Sac_Dper_Packeddata { get; set; }
        public string B650_Sac_Mper_Packeddata { get; set; }
        public string B650_Sac_Int_Packeddata { get; set; }
        public string B650_Sac_Term_Packeddata { get; set; }
        public string B650_Sac_Eff_Dt_Packeddata { get; set; }
        public string B650_Sac_Expir_Dt_Packeddata { get; set; }

        public string B650_Teaser_Rate_Packeddata { get; set; }
        public string B650_Teaser_Exp_Dt_Packeddata { get; set; }
        public string B650_Teaser_Dper_Rt_Packeddata { get; set; }
        public string B650_Teaser_Mper_Rt_Packeddata { get; set; }
        public string B650_Teaser_Term_Packeddata { get; set; }

        public string B650_Delq_Stat_Rate_Eff_Date_Packeddata { get; set; }
        public string B650_Delq_Stat_Rate_Packeddata { get; set; }
        public string B650_Curr_Stat_Rate_Eff_Date_Packeddata { get; set; }
        public string B650_Curr_Stat_Rate_Packeddata { get; set; }
        public string B650_Auto_Drft_Rate_Eff_Date_Packeddata { get; set; }
        public string B650_Auto_Drft_Rate_Packeddata { get; set; }
        public string B650_Empl_Disc_Rate_Eff_Date_Packeddata { get; set; }
        public string B650_Empl_Disc_Rate_Packeddata { get; set; }

        public string B650_Rate_Chg_Date { get; set; }
        public string B650_Prepay_Pen_Amt_Packeddata { get; set; }
        public string B650_Prin_Paid_Ytd_Packeddata { get; set; }
        public string B650_Esc_Paid_Ytd_Packeddata { get; set; }
        public string B_650_Fees_Paid_Ytd_Packeddata { get; set; }
        public string B650_Late_Chg_Paid_Ytd_Packeddata { get; set; }

        public string B650_Pmt_Due_Date_1 { get; set; }
        public string B650_Pmt_Paid_Date_1 { get; set; }
        public string B650_Pmt_Due_Date_2 { get; set; }
        public string B650_Pmt_Paid_Date_2 { get; set; }
        public string B650_Pmt_Due_Date_3 { get; set; }
        public string B650_Pmt_Paid_Date_3 { get; set; }
        public string B650_Pmt_Due_Date_4 { get; set; }
        public string B650_Pmt_Paid_Date_4 { get; set; }
        public string B650_Pmt_Due_Date_5 { get; set; }
        public string B650_Pmt_Paid_Date_5 { get; set; }
        public string B650_Pmt_Due_Date_6 { get; set; }
        public string B650_Pmt_Paid_Date_6 { get; set; }
        public string B650_Prin_Pd_Since_Lst_Stmt_Packeddata { get; set; }
        public string B650_Int_Pd_Since_Lst_Stmt_Packeddata { get; set; }

        public string B650_Esc_Pd_Since_Lst_Stmt_Packeddata { get; set; }

        public string B650_Lc_Pd_Since_Lst_Stmt_Packeddata { get; set; }
        public string B650_Fees_Pd_Since_Lst_Stmt_Packeddata { get; set; }

        public string B650_Amt_To_Uaf_Since_Lst_Stmt_Packeddata { get; set; }
        public string B650_Tot_Pd_Since_Lst_Stmt_Packeddata { get; set; }

        public string B650_Fees_Assd_Since_Lst_Stmt_Packeddata { get; set; }
        public string B650_Accr_Lc_Packeddata { get; set; }

        public string B650_Loss_Mit_Ind { get; set; }
        public string B650_1St_Contact_Name { get; set; }
        public string B650_1St_Contact_Adrs_1 { get; set; }
        public string B650_1St_Contact_City { get; set; }
        public string B650_1St_Contact_St { get; set; }
        public string B650_1St_Contact_Zip { get; set; }
        public string B650_1St_Contact_Phone { get; set; }
        public string B650_1St_Contact_Ph_Ext { get; set; }
        public string B650_Cash_Tran_Opt_Out { get; set; }
        public string B650_Mult_Loan_Ind { get; set; }
        public string B650_Last_Ann_Stmt_Dt_Packeddata { get; set; }
        public string B650_Last_Ann_Stmt_Meth { get; set; }
        public string B650_Opt_Out_Type { get; set; }
        public string B650_Opt_Out_Date_Packeddata { get; set; }
        public string B650_Special_Contact_Code { get; set; }
        public string B650_Last_Dscl_Notice_Dt_Packeddata { get; set; }
        public string B650_Last_Dscl_Notice_Meth { get; set; }
        public string B650_Prim_Opt_Out_Type { get; set; }
        public string B650_Prim_Opt_Out_Date_Packeddata { get; set; }
        public string B650_Scnd_Opt_Out_Type { get; set; }
        public string B650_Scnd_Opt_Out_Date_Packeddata { get; set; }
        public string B650_Cbwr1_Opt_Out_Type { get; set; }
        public string B650_Cbwr1_Opt_Out_Date_Packeddata { get; set; }
        public string B650_Cbwr2_Opt_Out_Type { get; set; }
        public string B650_Cbwr2_Opt_Out_Date_Packeddata { get; set; }
        public string B650_Cbwr3_Opt_Out_Type { get; set; }
        public string B650_Cbwr3_Opt_Out_Date_Packeddata { get; set; }
        public string B650_Cbwr4_Opt_Out_Type { get; set; }
        public string B650_Cbwr4_Opt_Out_Date_Packeddata { get; set; }
        public string B650_Cbwr5_Opt_Out_Type { get; set; }
        public string B650_Cbwr5_Opt_Out_Date_Packeddata { get; set; }
        public string B650_Cbwr6_Opt_Out_Type { get; set; }
        public string B650_Cbwr6_Opt_Out_Date_Packeddata { get; set; }
        public string B650_Cbwr7_Opt_Out_Type { get; set; }
        public string B650_Cbwr7_Opt_Out_Date_Packeddata { get; set; }

        public string B650_Cbwr8_Opt_Out_Type { get; set; }
        public string B650_Cbwr8_Opt_Out_Date_Packeddata { get; set; }
        public string B650_Cbwr9_Opt_Out_Type { get; set; }
        public string B650_Cbwr9_Opt_Out_Date_Packeddata { get; set; }
        public string B650_Cbwr10_Opt_Out_Type { get; set; }
        public string B650_Cbwr10_Opt_Out_Date_Packeddata { get; set; }
        public string B650_Accelerated_Dt_Packeddata { get; set; }

        public string B650_Accelerated_Interest_Amt_Packeddata { get; set; }
        public string B650_Print_Stmt { get; set; }
        public string B650_Limit_Reduction_Mths_Packeddata { get; set; }
        public string B650_Limit_Reduction_Amt_Packeddata { get; set; }
        public string B650_Cr_Limit_Reduce_Tot_Packeddata { get; set; }
        public string B650_Mat_Loan_Bill_Opt { get; set; }
        public string B650_Prim_Attention { get; set; }
        public string B650_Accelerated_Amt_Packeddata { get; set; }
        public string B650_Reinstatement_Dt_Packeddata { get; set; }
        public string B650_Reinstatement_Amt_Packeddata { get; set; }

        public string B650_Next_Draft_Dt_Packeddata { get; set; }
        public string B650_Breach_Date_Packeddata { get; set; }
        public string B650_Chrg_Off_Dt_Packeddata { get; set; }
        public string B650_Promise_Date_Packeddata { get; set; }
        public string B650_Promise_Amt_Packeddata { get; set; }
        public string B650_Promise_Broken_Dt_Packeddata { get; set; }
        public string B650_Promise_Kept_Date_Packeddata { get; set; }
        public string B650_Task605_Comp_Dt_Packeddata { get; set; }
        public string Filler { get; set; }


    }
}
