namespace HelocService.Models.InputCopyBookModels.MortgageLoanBillingModels
{
    public class TransactionRecordModel
    {
        public string B650_Rcd_Id { get; set; }
        public string B650_Inst { get; set; }
        public string B650_Acct_No { get; set; }
        public string B650_Seq_No { get; set; }
        public string B650_Log_Date_PackedData { get; set; }
        public string B650_Log_Time { get; set; }
        public string B650_Tr_Date_PackedData { get; set; }
        public string B650_Log_Ptrn { get; set; }
        public string B650_Tr_Fill_01 { get; set; }
        public string B650_Log_Tran { get; set; }
        public string B650_Tr_Fill_02 { get; set; }
        public string B650_Tr_Store_Ovride { get; set; }
        public string B650_Tr_Fill_03 { get; set; }
        public string B650_Tr_Amt_PackedData { get; set; }
        public string B650_Tr_Cash_Amt_PackedData { get; set; }
        public string B650_Tr_Teller_PackedData { get; set; }
        public string B650_Tr_Unap_Cd_Before { get; set; }
        public string B650_Tr_Unap_Cd_After { get; set; }
        public string B650_Tr_Amt_To_Prin_PackedData { get; set; }
        public string B650_Tr_Amt_To_Int_PackedData { get; set; }
        public string B650_Tr_Amt_To_Esc_PackedData { get; set; }
        public string B650_Tr_Amt_To_Lc_PackedData { get; set; }
        public string B650_Tr_Amt_To_Pvar_PackedData { get; set; }
        public string B650_Tr_Amt_To_Ivar_PackedData { get; set; }
        public string B650_Tr_Amt_To_Evar_PackedData { get; set; }
        public string B650_Tr_Amt_To_Lvar_PackedData { get; set; }
        public string B650_Tr_Amt_To_Lip_PackedData { get; set; }
        public string B650_Tr_Pymt_Ctr_PackedData { get; set; }
        public string B650_Tr_Amt_To_Cr_Ins_PackedData { get; set; }
        public string B650_Tr_Prin_Bal_PackedData { get; set; }
        public string B650_Tr_Esc_Bal_PackedData { get; set; }
        public string B650_Tr_Pd_To_Date_PackedData { get; set; }
        public string B650_Tr_Esc_Pymt_PackedData { get; set; }
        public string B650_Tr_Prn_Var_PackedData { get; set; }
        public string B650_Tr_Uncoll_Int_PackedData { get; set; }
        public string B650_Tr_Esc_Var_PackedData { get; set; }
        public string B650_Tr_Uncoll_Lc_PackedData { get; set; }
        public string B650_Tr_Dla_PackedData { get; set; }
        public string B650_Tr_Lip_Bal_PackedData { get; set; }
        public string B650_Tr_Lip_La_Date_PackedData { get; set; }
        public string B650_Tr_Pre_Int_Amt_PackedData { get; set; }
        public string B650_Tr_Pre_Int_Date { get; set; }
        public string B650_Tr_Amt_To_Fees_PackedData { get; set; }
        public string B650_Tr_Fee_Code { get; set; }
        public string B650_Tr_Fee_Desc { get; set; }
        public string B650_Tr_Amt_Negam_Tak_PackedData { get; set; }
        public string B650_Tr_Amt_Negam_Pd_PackedData { get; set; }
        public string B650_Tr_Esc_Pay_Id { get; set; }
        public string B650_Tr_Amort_Fee_Pymt { get; set; }

        public string B650_Tr_Amt_To_Unapplied_2 { get; set; }
        public string B650_Tr_Amt_To_Unapplied_3 { get; set; }
        public string B650_Tr_Amt_To_Unapplied_4 { get; set; }
        public string B650_Tr_Amt_To_Unapplied_5 { get; set; }
        public string B650_Tr_Last_Adv_Check { get; set; }
        public string B650_Tr_Last_Adv_Payee_Name { get; set; }
        public string B650_Filler_Reserved { get; set; }
        public string B650_Settle_Refer_Number { get; set; }
        public string B650_Tr_Settle_Merch_Org_Packeddata { get; set; }
        public string B650_Tr_Settle_Merch_Store_Packeddata { get; set; }
        public string B650_Tr_Settle_Store_Org_Packeddata { get; set; }
        public string B650_Tr_Settle_Store_Number_Packeddata { get; set; }
        public string B650_Tr_Settle_Tran_Cat_Packeddata { get; set; }
        public string B650_Tr_Settle_Merch_Info { get; set; }
        public string B650_Tr_Settle_Currency_Cd { get; set; }
        public string B650_Tr_Conv_Rate_Packeddata { get; set; }
        public string B650_Tr_Settle_Foreign_Amt_Packeddata { get; set; }
        public string B650_Tr_Amt_To_Pra_Remain { get; set; }
        public string B650_Tr_Amt_To_Def_Prin_Packeddata { get; set; }
        public string B650_Tr_Def_Prin_Bal_After_Packeddata { get; set; }
        public string B650_Tr_Amt_To_Def_Int_Packeddata { get; set; }
        public string B650_Tr_Def_Int_Bal_Aft_Packeddata { get; set; }
        public string B650_Tr_Amt_To_Def_Late_Chrg_Packeddata { get; set; }
        public string B650_Tr_Def_Lt_Chg_Bal_Aft_Packeddata { get; set; }
        public string B650_Tr_Amt_To_Def_Esc_Adv_Packeddata { get; set; }
        public string B650_Tr_Def_Esc_Adv_Bal_Aft_Packeddata { get; set; }
        public string B650_Tr_Amt_To_Def_Pd_Exp_Adv_Packeddata { get; set; }
        public string B650_Tr_Def_Pd_Exp_Adv_Bal_Aft_Packeddata { get; set; }
        public string B650_Tr_Amt_To_Def_Unp_Exp_Adv_Packeddata { get; set; }
        public string B650_Tr_Def_Unpexp_Adv_Bal_Aft_Packeddata { get; set; }
        public string B650_Tr_Amt_To_Def_Admn_Fees_Packeddata { get; set; }
        public string B650_Tr_Def_Admn_Fees_Bal_Aft_Packeddata { get; set; }
        public string B650_Tr_Amt_To_Def_Optins_Packeddata { get; set; }
        public string B650_Tr_Def_Optins_Bal_Aft_Packeddata { get; set; }
        public string B650_Filler1 { get; set; }

    }
}
